hotfix(model.py): more robust regression logic
The existing regression logic breaks when horizontal_regr is not None but
vertical_regr is None, as shown by this stack trace:

```
AttributeError: 'NoneType' object has no attribute 'rvalue'
Traceback:
File "/home/sbs/src/github.com/tn-aixpa/overtourism/overtourism/dashboard.py", line 17, in on_change
    st.session_state.edit_model.update(edit_values)
File "/home/sbs/src/github.com/tn-aixpa/overtourism/overtourism/viz_model.py", line 219, in update
    self._build()
File "/home/sbs/src/github.com/tn-aixpa/overtourism/overtourism/viz_model.py", line 99, in _build
    modals = self.model.compute_modal_line_per_constraint()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/sbs/src/github.com/tn-aixpa/overtourism/.venv/lib/python3.12/site-packages/dt_model/model/model.py", line 166, in compute_modal_line_per_constraint
    elif (horizontal_regr is None) or (horizontal_regr.rvalue < vertical_regr.rvalue):
                                                                ^^^^^^^^^^^^^^^^^^^^
```

This diff implements a hotfix attempting to make the code more robust without
changing the existing logic. To this end, I did the following:

1. factor the logic for setting the points into common functions

2. moved the check for using the rvalue comparison where we are sure
both vertical_regr and horizontal_regr are defined

3. reorder the if chain to ensure we progress from both being defined to
just one of them being defined to none of them being defined

Closes https://github.com/tn-aixpa/overtourism/issues/2.

Closes https://github.com/tn-aixpa/dt-model/issues/7.